name: "build-test"
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.toolchain }}
          cache-base: master
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build
      - name: Start nginx
        run: cd test-support && docker compose up -d
      - run: cargo test
