name: "build-test"
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:master,network=host
      # - name: Expose GitHub Runtime
      #   uses: crazy-max/ghaction-github-runtime@v4
      # - run: |
      #     docker buildx build \
      #       --cache-from "type=gha" \
      #       --cache-to "type=gha" \
      #       -t test .
      - name: Cache
        uses: actions/cache@v6
        with:
          path: /tmp/t
          key: ${{ runner.os }}-docker-build-cache
      - run: ls -la /tmp/t
      - run: mkdir -p /tmp/t && docker buildx build --cache-from type=local,src=/tmp/t --cache-to type=local,dest=/tmp/t -t test .
      # - name: Build and push
      #   uses: docker/build-push-action@v7
      #   with:
      #     context: .
      #     tags: "test:latest"
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
